services:
  - type: web
    name: ai-image-generator
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser
      pip install -r requirements.txt
    startCommand: "./start.sh"
    envVars:
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false