services:
  - type: web
    name: ai-image-generator
    runtime: python
    buildCommand: | 
      apt-get update && apt-get install -y wget ca-certificates gnupg
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
      apt-get update && apt-get install -y google-chrome-stable
      pip install -r requirements.txt
    startCommand: "bash start.sh"
    envVars:
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false