services:
  - type: web
    name: ai-image-generator
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false