services:
  - type: web
    name: ai-image-generator
    runtime: python
    buildCommand: |
      echo "Starting build..."
      apt-get update && apt-get install -y wget unzip curl
      echo "Installing Chrome..."
      curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
      apt-get update && apt-get install -y google-chrome-stable
      echo "Build completed!"
    startCommand: "bash start.sh"
    envVars:
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false
