services:
  - type: web
    name: ai-image-generator
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y wget curl unzip
      wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome.deb
      rm google-chrome.deb
      pip install -r requirements.txt
    startCommand: "./start.sh"
    envVars:
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false
