services:
  - type: web
    name: ai-image-generator
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y wget unzip
      wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb
      rm google-chrome-stable_current_amd64.deb
    startCommand: "bash start.sh"
    envVars:
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false